### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by shirohako** [HanSon/img#3]
`git clone https://github.com/HanSon/img.git`
用git版本的打开直接就是Whoops, looks like something went wrong.

用composer的版本前台OK
选择文件后500
LOG.error: Symfony\Component\Debug\FatalThrowableError: Class GuzzleHttp\Client not found

**Comment by Hanson** [comment]
看一下vendor有没有guzzle 包

**Comment by shirohako** [comment]
没有,composer也没报错..

**Comment by Hanson** [comment]
你试试 composer require guzzlehttp/guzzle

**Comment by shirohako** [comment]
guzzle解决了
点击上传后浏览器弹出了
![image](https://ooo.0o0.ooo/2017/06/19/59479ca60ef3e.jpg)

**Comment by Hanson** [comment]
google一下证书 ssl certificate 吧

**Comment by shirohako** [comment]
也就是说我需要在https下才能使图床工作?

**Comment by Hanson** [comment]
不是。你看我网站就知道了，这个是很常见的问题，google能找到的

**Comment by shirohako** [comment]
`"guzzlehttp/guzzle": "~4.0"`
我尝试降低了guzzlehttp的版本.
但没有成功![i](https://ooo.0o0.ooo/2017/06/19/5947a14e47680.jpg)

**Comment by Hanson** [comment]
为什么要降低版本呢，尝试 加上 verify => false 的配置

**Comment by shirohako** [comment]
我尝试在config/app.php中加上了这项配置,没有成功
请指教是加在这里吗

**Comment by Hanson** [comment]
guzzle的配置。

**Comment by shirohako** [comment]
Class UploadController 的uploadToSM方法吗..

**Comment by Hanson** [comment]
你把错误信息复制到搜索引擎去找解决方法比较靠谱

**Comment by shirohako** [comment]
我尝试改了 vendor/guzzlehttp/guzzle/src/Client.php下的配置.
尝试了几次,正常工作了.
感谢

**Comment by shirohako** [comment]
尝试了另外2种方法

$client = new Client([ 'verify' => false ]); 
work

adding 'guzzle' => ['verify' => false] in config/services.php
can't work
